language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - 1.12beta2
  - tip
install:
  - go get -v github.com/golang/dep/cmd/dep honnef.co/go/tools/cmd/staticcheck
  - dep ensure -v
script:
  - staticcheck
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success: bash <(curl -s https://codecov.io/bash)
