language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
install:
  - if [[ $DEP_TOOL == "dep" ]]; then GO111MODULE=off go get -v github.com/golang/dep/cmd/dep honnef.co/go/tools/cmd/staticcheck; fi
  - if [[ $DEP_TOOL == "mod" ]]; then go get honnef.co/go/tools/cmd/staticcheck@master; fi
  - if [[ $DEP_TOOL == "dep" ]]; then dep ensure -v; fi
  - if [[ $DEP_TOOL == "mod" ]]; then go mod download; fi
script:
  - staticcheck
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success: bash <(curl -s https://codecov.io/bash)
env:
  matrix:
    - DEP_TOOL=dep GO111MODULE=off
    - DEP_TOOL=mod GO111MODULE=on
go:
  - 1.10.x
  - 1.11.x
  - 1.12beta2
  - tip
matrix:
  fast_finish: true
  exclude:
    - go: 1.10.x
      env: DEP_TOOL=mod GO111MODULE=on
    - go: 1.10.x
      env: DEP_TOOL=mod GO111MODULE=on
