
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-cleanhttp"

[prune]
  go-tests = true
  unused-packages = true
