
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/hashicorp/go-cleanhttp"
  version = "0.5.0"

[prune]
  go-tests = true
  unused-packages = true
